### ISSUE TITLE
No such file or directory: 'config/los_model.state'

### ISSUE THREAD

**Issue by BrianBut** [nhsx/skunkworks-long-stayer-risk-stratification#11]
In local deployment of development server.
$ FLASK_APP=ltss:create_app FLASK_ENV=development FLASK_DEBUG=1 python3 -m flask run --host=0.0.0.0 fails with 
* Serving Flask app 'ltss:create_app' (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 845, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 321, in __init__
    self._load_unlocked()
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 346, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 402, in load_app
    app = locate_app(self, import_name, name)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 275, in locate_app
    return find_app_by_string(script_info, module, app_name)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 201, in find_app_by_string
    app = call_factory(script_info, attr, args, kwargs)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory(*args, **kwargs)
  File "/home/brian/Beds/skunkworks-long-stayer-risk-stratification/ltss/__init__.py", line 47, in create_app
    initialise_models()
  File "/home/brian/Beds/skunkworks-long-stayer-risk-stratification/ltss/__init__.py", line 36, in initialise_models
    LOS_MODEL = los_model.init_model()
  File "/home/brian/Beds/skunkworks-long-stayer-risk-stratification/ltss/los_model.py", line 95, in init_model
    predictor.load_state_dict(torch.load(model_file, map_location=torch.device('cpu')))
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/brian/anaconda3/envs/beds/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'config/los_model.state'

**Comment by amadeuspzs** [comment]
Hi @BrianBut if you follow the instructions at https://github.com/nhsx/skunkworks-long-stayer-risk-stratification/blob/main/training/README.md#training-model-and-creating-the-files-needed-to-test-the-repo this will help generate the data and train the missing model
